#!/usr/bin/env python3
"""
49_make_storage_operation_figure.py

Appendix figure: representative storage operation during a shortage event.
Three vertically stacked panels (load shedding, storage discharge, SOC)
comparing Emergency-only storage MCS, Event-window storage MCS, and Full-year ED.

Source data:
  results/storage_operation_comparison/event_window.csv
  (generated by scripts/48_generate_storage_operation_dispatch.jl)

Event: Scenario 15, balanced VRE portfolio, N=20, seed=42.
  First shedding hour h4983 (rel 0). Display window h4959–h5048 (90 hours).
  EUE identical across all three methods (8060 MWh in window).
  M2 (Event-window storage MCS) redistributes shedding differently, with
  one additional shedding hour and a higher maximum shortfall (1440 vs 1348 MW).

Outputs (figures/):
  storage_operation_comparison.pdf
  storage_operation_comparison.png
"""

import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(REPO, "results", "storage_operation_comparison", "event_window.csv")
FIG  = os.path.join(REPO, "figures")
os.makedirs(FIG, exist_ok=True)

plt.rcParams.update({
    "figure.facecolor":   "white",
    "axes.facecolor":     "white",
    "axes.edgecolor":     "#333333",
    "axes.linewidth":     0.8,
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size":          9,
    "axes.labelsize":     9,
    "axes.titlesize":     9,
    "xtick.labelsize":    8,
    "ytick.labelsize":    8,
    "legend.fontsize":    7.5,
    "legend.framealpha":  0.92,
    "legend.edgecolor":   "#cccccc",
    "savefig.dpi":        300,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.05,
    "pdf.fonttype":       42,
    "ps.fonttype":        42,
})

C_M1C = "#1565C0"   # Emergency-only storage MCS — blue
C_M2  = "#2E7D32"   # Event-window storage MCS  — green
C_M3  = "#C62828"   # Full-year ED               — red/crimson

LW_MAIN = 1.4
LW_M3   = 1.2   # Full-year ED drawn dashed, slightly thinner

# ─────────────────────────────────────────────────────────────────────────────
# Load data
# ─────────────────────────────────────────────────────────────────────────────

df = pd.read_csv(DATA)
df = df.sort_values("hour").reset_index(drop=True)

rel  = df["rel_hour"].values

ls_m1c = df["m1c_load_shed_mw"].values
ls_m2  = df["m2_load_shed_mw"].values
ls_m3  = df["m3_load_shed_mw"].values

dc_m1c = df["m1c_storage_discharge_mw"].values
dc_m2  = df["m2_storage_discharge_mw"].values
dc_m3  = df["m3_storage_discharge_mw"].values

soc_m1c = df["m1c_soc_mwh"].values
soc_m2  = df["m2_soc_mwh"].values
soc_m3  = df["m3_soc_mwh"].values

# Verify EUE balance
eue_m1c = ls_m1c.sum()
eue_m2  = ls_m2.sum()
eue_m3  = ls_m3.sum()
print(f"Window EUE — Emergency-only MCS: {eue_m1c:.1f}  "
      f"Event-window MCS: {eue_m2:.1f}  Full-year ED: {eue_m3:.1f}  MWh")
assert abs(eue_m1c - eue_m2) < 1.0 and abs(eue_m1c - eue_m3) < 1.0, \
    "EUE mismatch across methods"

# ─────────────────────────────────────────────────────────────────────────────
# Shortage-window shading boundaries (hours where any method sheds > 0)
# ─────────────────────────────────────────────────────────────────────────────

any_shed = (ls_m1c > 0) | (ls_m2 > 0) | (ls_m3 > 0)
shed_rel = rel[any_shed]
if len(shed_rel):
    shade_lo = shed_rel.min() - 0.5
    shade_hi = shed_rel.max() + 0.5
else:
    shade_lo, shade_hi = -0.5, 0.5

storage_capacity_mwh = 3932.0   # VRE120_base: 983 MW × 4 h

# ─────────────────────────────────────────────────────────────────────────────
# Figure
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(3, 1, figsize=(6.8, 7.0),
                         sharex=True,
                         gridspec_kw={"hspace": 0.10})

ax_ls, ax_dc, ax_soc = axes

shade_kw = dict(color="#F5F5F5", zorder=0)

for ax in axes:
    ax.axvspan(shade_lo, shade_hi, **shade_kw)
    ax.axvline(0, color="#888888", lw=0.6, ls="--", zorder=1)
    ax.grid(axis="y", alpha=0.20)
    ax.set_axisbelow(True)

# ── (a) Load shedding ────────────────────────────────────────────────────────

ax_ls.step(rel, ls_m3,  where="post", color=C_M3,  lw=LW_M3,
           ls="--", zorder=3, label="Full-year ED")
ax_ls.step(rel, ls_m1c, where="post", color=C_M1C, lw=LW_MAIN,
           zorder=4, label="Emergency-only storage MCS")
ax_ls.step(rel, ls_m2,  where="post", color=C_M2,  lw=LW_MAIN,
           zorder=5, label="Event-window storage MCS")

ax_ls.set_ylabel("Load shedding (MW)")
ax_ls.set_title("Representative storage operation during shortage event",
                fontsize=9.5, fontweight="bold", pad=5)
ymax_ls = max(ls_m1c.max(), ls_m2.max(), ls_m3.max())
ax_ls.set_ylim(0, ymax_ls * 1.30)

# Annotate the M2-only hours
m2_only_mask = (ls_m2 > 0) & (ls_m1c == 0)
if m2_only_mask.any():
    m2_only_rel = rel[m2_only_mask]
    m2_only_val = ls_m2[m2_only_mask]
    ax_ls.scatter(m2_only_rel, m2_only_val,
                  color=C_M2, marker="^", s=28, zorder=6,
                  label="_m2_only")

# EUE note
ax_ls.text(0.98, 0.97,
           f"Window EUE: {eue_m1c:,.0f} MWh (identical for all methods)",
           transform=ax_ls.transAxes, fontsize=6.2, color="#333333",
           ha="right", va="top",
           bbox=dict(boxstyle="round,pad=0.20", facecolor="#F5F5F5",
                     edgecolor="#cccccc", lw=0.6))

ax_ls.text(shade_lo + (shade_hi - shade_lo) * 0.02,
           ymax_ls * 1.22,
           "Shortage\nwindow", fontsize=6.0, color="#666666",
           style="italic", va="top")

# ── (b) Storage discharge ────────────────────────────────────────────────────

ax_dc.step(rel, dc_m3,  where="post", color=C_M3,  lw=LW_M3,
           ls="--", zorder=3)
ax_dc.step(rel, dc_m1c, where="post", color=C_M1C, lw=LW_MAIN, zorder=4)
ax_dc.step(rel, dc_m2,  where="post", color=C_M2,  lw=LW_MAIN, zorder=5)

ax_dc.axhline(983.0, color="#AAAAAA", lw=0.7, ls=":", zorder=2)
ax_dc.text(rel[-1] - 1, 983.0 + 15, "Max power\n(983 MW)",
           fontsize=5.5, color="#777777", ha="right", va="bottom")

ax_dc.set_ylabel("Storage discharge (MW)")
ymax_dc = max(dc_m1c.max(), dc_m2.max(), dc_m3.max())
ax_dc.set_ylim(0, ymax_dc * 1.18)

# ── (c) State of charge ──────────────────────────────────────────────────────

ax_soc.plot(rel, soc_m3,  color=C_M3,  lw=LW_M3,   ls="--", zorder=3)
ax_soc.plot(rel, soc_m1c, color=C_M1C, lw=LW_MAIN, zorder=4)
ax_soc.plot(rel, soc_m2,  color=C_M2,  lw=LW_MAIN, zorder=5)

ax_soc.axhline(storage_capacity_mwh, color="#AAAAAA", lw=0.7, ls=":", zorder=2)
ax_soc.text(rel[-1] - 1, storage_capacity_mwh + 50,
            f"Capacity ({storage_capacity_mwh/1000:.1f} GWh)",
            fontsize=5.5, color="#777777", ha="right", va="bottom")
ax_soc.axhline(0, color="#CCCCCC", lw=0.5, zorder=1)

ax_soc.set_ylabel("State of charge (MWh)")
ax_soc.set_ylim(-100, storage_capacity_mwh * 1.12)

# ── Shared x-axis ────────────────────────────────────────────────────────────

ax_soc.set_xlabel("Hour relative to first shedding hour")
ax_soc.set_xlim(rel[0] - 0.5, rel[-1] + 0.5)

# Tick every 12 hours, label every 24
tick_step = 12
ticks = np.arange(
    int(np.ceil(rel[0] / tick_step)) * tick_step,
    rel[-1] + 1,
    tick_step,
    dtype=int,
)
ax_soc.set_xticks(ticks)
ax_soc.set_xticklabels(
    [str(t) if t % 24 == 0 else "" for t in ticks],
    fontsize=7.5
)
for ax in axes[:-1]:
    ax.set_xticks(ticks)

# ── Legend on panel (a) ──────────────────────────────────────────────────────

legend_handles = [
    Line2D([0], [0], color=C_M1C, lw=LW_MAIN, label="Emergency-only storage MCS"),
    Line2D([0], [0], color=C_M2,  lw=LW_MAIN, label="Event-window storage MCS"),
    Line2D([0], [0], color=C_M3,  lw=LW_M3, ls="--", label="Full-year ED"),
]
ax_ls.legend(handles=legend_handles, loc="upper left", fontsize=7.2,
             framealpha=0.92, edgecolor="#cccccc")

# Panel labels
for ax, lbl in zip(axes, ["(a)", "(b)", "(c)"]):
    ax.text(0.005, 0.97, lbl, transform=ax.transAxes,
            fontsize=8.5, fontweight="bold", va="top")

fig.tight_layout()

for ext in ("pdf", "png"):
    out = os.path.join(FIG, f"storage_operation_comparison.{ext}")
    fig.savefig(out, format=ext)
    print(f"  storage_operation_comparison.{ext}")
plt.close(fig)

print(f"\nDone.  Scenario 15, balanced VRE, window {df['hour'].iloc[0]}–{df['hour'].iloc[-1]}.")
