#!/usr/bin/env python3
"""
50_make_storage_operation_compact.py

Compact main-text figure: storage operation during a representative
shortage event (balanced VRE, Scenario 15, rel hours -8 to +10).

Three panels:
  (a) Load shedding (MW)
  (b) Aggregate storage discharge (MW)
  (c) Aggregate state of charge (MWh)

Source data:
  results/storage_operation_comparison/event_window.csv
  (generated by scripts/48_generate_storage_operation_dispatch.jl)

Outputs (figures/):
  storage_operation_comparison_compact.pdf
  storage_operation_comparison_compact.png
"""

import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

# ─────────────────────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────────────────────

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
DATA = os.path.join(REPO, "results", "storage_operation_comparison", "event_window.csv")
FIG  = os.path.join(REPO, "figures")
os.makedirs(FIG, exist_ok=True)

# ─────────────────────────────────────────────────────────────────────────────
# Style
# ─────────────────────────────────────────────────────────────────────────────

plt.rcParams.update({
    "figure.facecolor":   "white",
    "axes.facecolor":     "white",
    "axes.edgecolor":     "#333333",
    "axes.linewidth":     0.8,
    "font.family":        "sans-serif",
    "font.sans-serif":    ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size":          8.5,
    "axes.labelsize":     8.5,
    "xtick.labelsize":    7.5,
    "ytick.labelsize":    7.5,
    "legend.fontsize":    7.2,
    "legend.framealpha":  0.90,
    "legend.edgecolor":   "#cccccc",
    "legend.handlelength": 2.0,
    "savefig.dpi":        300,
    "savefig.bbox":       "tight",
    "savefig.pad_inches": 0.05,
    "pdf.fonttype":       42,
    "ps.fonttype":        42,
})

# Emergency-only MCS / Full-year ED (overlap in load shed and discharge)
C_M1C = "#1565C0"   # solid blue — Emergency-only storage MCS
C_M2  = "#2E7D32"   # solid green — Event-window storage MCS
C_M3  = "#E65100"   # dashed orange — Full-year ED

LW    = 1.5   # main linewidth
LW_M3 = 1.0   # Full-year ED: thinner + dashed so M1c shows through

STORAGE_CAPACITY_MWH = 3932.0   # VRE120_base: 983 MW × 4 h

# ─────────────────────────────────────────────────────────────────────────────
# Data
# ─────────────────────────────────────────────────────────────────────────────

df_all = pd.read_csv(DATA).sort_values("rel_hour").reset_index(drop=True)

REL_LO, REL_HI = -8, 10
mask = (df_all["rel_hour"] >= REL_LO) & (df_all["rel_hour"] <= REL_HI)
df = df_all[mask].copy()

rel = df["rel_hour"].values

ls_m1c = df["m1c_load_shed_mw"].values
ls_m2  = df["m2_load_shed_mw"].values
ls_m3  = df["m3_load_shed_mw"].values

dc_m1c = df["m1c_storage_discharge_mw"].values
dc_m2  = df["m2_storage_discharge_mw"].values
dc_m3  = df["m3_storage_discharge_mw"].values

soc_m1c = df["m1c_soc_mwh"].values
soc_m2  = df["m2_soc_mwh"].values
soc_m3  = df["m3_soc_mwh"].values

# Compute sub-window EUE
eue_m1c = ls_m1c.sum()
eue_m2  = ls_m2.sum()
eue_m3  = ls_m3.sum()
print(f"Local-window EUE — Emergency-only MCS: {eue_m1c:.1f}  "
      f"Event-window MCS: {eue_m2:.1f}  Full-year ED: {eue_m3:.1f}  MWh")

# ─────────────────────────────────────────────────────────────────────────────
# Figure layout
# ─────────────────────────────────────────────────────────────────────────────

fig, axes = plt.subplots(
    3, 1,
    figsize=(5.5, 5.8),
    sharex=True,
    gridspec_kw={"hspace": 0.08, "top": 0.97, "bottom": 0.09,
                 "left": 0.13, "right": 0.97},
)
ax_ls, ax_dc, ax_soc = axes

# Shared x limits
x_lo = REL_LO - 0.5
x_hi = REL_HI + 0.5

# Subtle vertical marker at the first shedding hour (rel = 0)
for ax in axes:
    ax.axvline(0, color="#999999", lw=0.7, ls="--", zorder=1,
               label="_zero")
    ax.grid(axis="y", alpha=0.18, linewidth=0.5)
    ax.set_axisbelow(True)
    ax.set_xlim(x_lo, x_hi)

# ─────────────────────────────────────────────────────────────────────────────
# (a) Load shedding
# ─────────────────────────────────────────────────────────────────────────────

# Full-year ED drawn first (dashed, thinner) so M1c covers it where they overlap
ax_ls.step(rel, ls_m3,  where="post", color=C_M3,  lw=LW_M3, ls="--", zorder=3)
ax_ls.step(rel, ls_m1c, where="post", color=C_M1C, lw=LW,    zorder=4)
ax_ls.step(rel, ls_m2,  where="post", color=C_M2,  lw=LW,    zorder=5)

ax_ls.set_ylabel("Load shedding (MW)")
ymax_ls = max(ls_m1c.max(), ls_m2.max(), ls_m3.max())
ax_ls.set_ylim(-20, ymax_ls * 1.38)
ax_ls.yaxis.set_major_formatter(
    matplotlib.ticker.FuncFormatter(lambda x, _: f"{int(x):,}" if x >= 0 else "")
)

# Legend
legend_handles = [
    Line2D([0], [0], color=C_M1C, lw=LW,
           label="Emergency-only storage MCS"),
    Line2D([0], [0], color=C_M2,  lw=LW,
           label="Event-window storage MCS"),
    Line2D([0], [0], color=C_M3,  lw=LW_M3, ls="--",
           label="Full-year ED"),
]
ax_ls.legend(handles=legend_handles, loc="upper right",
             fontsize=7.0, framealpha=0.90, edgecolor="#cccccc",
             handlelength=2.2, handleheight=0.9,
             borderpad=0.4, labelspacing=0.3)

ax_ls.text(0.014, 0.96, "(a)", transform=ax_ls.transAxes,
           fontsize=8.5, fontweight="bold", va="top")

# Annotate "first shedding hour" on the x-axis reference line
ax_ls.annotate("first\nshedding\nhour",
               xy=(0, -20), xytext=(-3.5, ymax_ls * 0.72),
               fontsize=6.0, color="#777777", ha="center",
               arrowprops=dict(arrowstyle="-", color="#AAAAAA",
                               lw=0.6, shrinkA=0, shrinkB=2))

# ─────────────────────────────────────────────────────────────────────────────
# (b) Storage discharge
# ─────────────────────────────────────────────────────────────────────────────

ax_dc.step(rel, dc_m3,  where="post", color=C_M3,  lw=LW_M3, ls="--", zorder=3)
ax_dc.step(rel, dc_m1c, where="post", color=C_M1C, lw=LW,    zorder=4)
ax_dc.step(rel, dc_m2,  where="post", color=C_M2,  lw=LW,    zorder=5)

# Max-power reference line
ax_dc.axhline(983.0, color="#BBBBBB", lw=0.6, ls=":", zorder=2)
ax_dc.text(x_hi - 0.2, 983.0 + 30, "983 MW",
           fontsize=6.2, color="#888888", ha="right", va="bottom")

ax_dc.set_ylabel("Storage discharge (MW)")
ymax_dc = max(dc_m1c.max(), dc_m2.max(), dc_m3.max())
ax_dc.set_ylim(-20, ymax_dc * 1.18)

ax_dc.text(0.014, 0.96, "(b)", transform=ax_dc.transAxes,
           fontsize=8.5, fontweight="bold", va="top")

# ─────────────────────────────────────────────────────────────────────────────
# (c) State of charge
# ─────────────────────────────────────────────────────────────────────────────

ax_soc.plot(rel, soc_m3,  color=C_M3,  lw=LW_M3, ls="--", zorder=3)
ax_soc.plot(rel, soc_m1c, color=C_M1C, lw=LW,    zorder=4)
ax_soc.plot(rel, soc_m2,  color=C_M2,  lw=LW,    zorder=5)

# Capacity line
ax_soc.axhline(STORAGE_CAPACITY_MWH, color="#BBBBBB", lw=0.6, ls=":", zorder=2)
ax_soc.text(x_hi - 0.2, STORAGE_CAPACITY_MWH + 90,
            f"{STORAGE_CAPACITY_MWH/1000:.1f} GWh",
            fontsize=6.2, color="#888888", ha="right", va="bottom")

ax_soc.set_ylabel("State of charge (MWh)")
ax_soc.set_ylim(-100, STORAGE_CAPACITY_MWH * 1.13)
ax_soc.yaxis.set_major_locator(matplotlib.ticker.MultipleLocator(1000))

ax_soc.text(0.014, 0.96, "(c)", transform=ax_soc.transAxes,
            fontsize=8.5, fontweight="bold", va="top")

# ─────────────────────────────────────────────────────────────────────────────
# Shared x-axis
# ─────────────────────────────────────────────────────────────────────────────

ticks = np.arange(REL_LO, REL_HI + 1, 2)
ax_soc.set_xticks(ticks)
ax_soc.set_xticklabels([f"{t:+d}" if t != 0 else "0" for t in ticks])
ax_soc.set_xlabel("Hour relative to first shedding hour")

# ─────────────────────────────────────────────────────────────────────────────
# Save
# ─────────────────────────────────────────────────────────────────────────────

for ext in ("pdf", "png"):
    out = os.path.join(FIG, f"storage_operation_comparison_compact.{ext}")
    fig.savefig(out, format=ext)
    print(f"  storage_operation_comparison_compact.{ext}")
plt.close(fig)

print(f"\nDone.  Window rel {REL_LO}–{REL_HI} "
      f"(h{df['hour'].iloc[0]}–h{df['hour'].iloc[-1]}).")
print(f"EUE in window: M1c={eue_m1c:.0f}  M2={eue_m2:.0f}  M3={eue_m3:.0f} MWh")
